---
title: "data generation"
author: "Kara Belknap"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Generation

The following code was used to generate and manipulate the data set.

```{r cars}
library(tidyverse)
library(knitr)
library(shiny)
library(shinydashboard)
library(DT)
library(Lahman)
library(mathjaxr)
library(caret)
library(randomForest)


data("Teams")

#Narrow Data down to 1981-2021
teamsSubset <- Teams %>%
  filter(yearID>1980 & yearID<2022) 

#Changing all Angels teams to "Los Angeles Angels"
teamsSubset$name[teamsSubset$name == "California Angels"] <- "Los Angeles Angels"
teamsSubset$name[teamsSubset$name == "Anaheim Angels"] <- "Los Angeles Angels"
teamsSubset$name[teamsSubset$name == "Los Angeles Angels of Anaheim"] <- "Los Angeles Angels"

#Changing Tampa Bay Devil Rays to "Tampa Bay Rays"
teamsSubset$name[teamsSubset$name == "Tampa Bay Devil Rays"] <- "Tampa Bay Rays"

#Changing Florida Marlins to "Miami Marlins"
teamsSubset$name[teamsSubset$name == "Florida Marlins"] <- "Miami Marlins"

#Changing Cleveland Indians to Cleveland Guardians.
teamsSubset$name[teamsSubset$name == "Cleveland Indians"] <- "Cleveland Guardians"

#Montreal Expos moved to Washington Nationals in 2005. For Simplicity, merging these teams under Washington Nationals since they belong to the same franchise.... 
teamsSubset$name[teamsSubset$name == "Montreal Expos"] <- "Washington Nationals"

# No Post-Season play in 1994. Replacing NA values with "N". 
teamsSubset$WSWin[is.na(teamsSubset$WSWin)] <- "N"
teamsSubset$LgWin[is.na(teamsSubset$LgWin)] <- "N"

# Change Astros & Brewers to their respective current leagues
teamsSubset$lgID[teamsSubset$franchID == "HOU"] <- "AL"
teamsSubset$lgID[teamsSubset$franchID == "MIL"] <- "NL"

#assign current divisions
teamsSubset$divID[teamsSubset$divID == "E"] <- "East"
teamsSubset$divID[teamsSubset$divID == "W"] <- "West"
teamsSubset$divID[teamsSubset$divID == "C"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "ATL"] <- "East"
teamsSubset$divID[teamsSubset$franchID == "STL"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "CHC"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "MIL"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "PIT"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "CIN"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "CLE"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "CHW"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "MIN"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "DET"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "KCR"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "HOU"] <- "West"


# rename variables for display purposes.
teamsSubset <- rename(teamsSubset, league = lgID,
                      team = name, division = divID,
                      fieldingPct = FP, 
                      worldSeriesWin = WSWin, 
                      leagueWin = LgWin)

#adding new columns
teamSubsetMutate <- teamsSubset %>%
  mutate(pctGamesWon = W/(W+L)*100, 
         avgRunsScored = R/G, 
         avgHits = H/G,
         avgTotalBases = ((H + X2B + 2*X3B + 3*HR)/G), 
         avgHomeRuns = HR/G,
         avgWalks = BB/G,
         avgRunsAllowed = RA/G,
         avgHitsAllowed = HA/G,
         avgHomeRunsAllowed = HRA/G,
         avgWalksAllowed = BBA/G,
         avgErrors = E/G) %>%
  rename(year = yearID)

#removing columns that won't be used in final analysis
teamSubsetFinal <- teamSubsetMutate %>%
  select(-W, -L, -WCWin, -DivWin, -X2B, -X3B, 
         -AB, -SB, -CS, -HBP, -SF, -IPouts, -SO,
         -DP, -BPF, -PPF, -teamIDBR, -teamIDlahman45, 
         -teamIDretro, -Rank, -CG, -Ghome, -teamID, 
         -ER, -CG, -SHO, -SV, -SOA, -R, -H, -HR, -BB,
         -RA, -HA, -HRA, -BBA, -E, -park, -G, -attendance)

#data manipulation which will be used on the data page
col_order <- c("year", "league", "division",
               "team", "pctGamesWon", "avgRunsScored", "avgHits", 
               "avgTotalBases", "avgHomeRuns", "avgWalks", "avgRunsAllowed", 
               "ERA", "avgHitsAllowed", "avgHomeRunsAllowed", "avgWalksAllowed", 
               "avgErrors", "fieldingPct", "leagueWin", "worldSeriesWin")

#reorder columns for user output
teamSubsetFinal_reorder <- teamSubsetFinal[ , col_order]

#round numbers for display purposes.
userDataRaw <- teamSubsetFinal_reorder %>%
  mutate_if(is.numeric, round, 2) 



```
