---
title: "ST558 Project Testing"
author: "Kara Belknap"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library, warning=FALSE}
library(tidyverse)
library(knitr)
library(shiny)
library(shinydashboard)
library(Lahman)

```


```{r data}
data("Teams")

#Narrow Data down to 1981-2021
teamsSubset <- Teams %>%
  filter(yearID>1980) 

#Changing all Angels teams to "Los Angeles Angels"
teamsSubset$name[teamsSubset$name == "California Angels"] <- "Los Angeles Angels"
teamsSubset$name[teamsSubset$name == "Anaheim Angels"] <- "Los Angeles Angels"
teamsSubset$name[teamsSubset$name == "Los Angeles Angels of Anaheim"] <- "Los Angeles Angels"

#Changing Tampa Bay Devil Rays to "Tampa Bay Rays"
teamsSubset$name[teamsSubset$name == "Tampa Bay Devil Rays"] <- "Tampa Bay Rays"

#Changing Florida Marlins to "Miami Marlins"
teamsSubset$name[teamsSubset$name == "Florida Marlins"] <- "Miami Marlins"

#Changing Cleveland Indians to Cleveland Guardians.
teamsSubset$name[teamsSubset$name == "Cleveland Indians"] <- "Cleveland Guardians"

#Montreal Expos moved to Washington Nationals in 2005. For Simplicity, merging these teams under Washington Nationals since they belong to the same franchise.... 
teamsSubset$name[teamsSubset$name == "Montreal Expos"] <- "Washington Nationals"

# No Post-Season play in 1994. Replacing NA values with "N". 
teamsSubset$WSWin[is.na(teamsSubset$WSWin)] <- "N"
teamsSubset$LgWin[is.na(teamsSubset$LgWin)] <- "N"

# Change Astros & Brewers to their respective current leagues
teamsSubset$lgID[teamsSubset$franchID == "HOU"] <- "AL"
teamsSubset$lgID[teamsSubset$franchID == "MIL"] <- "NL"

str(teamsSubset)

#assign current divisions
teamsSubset$divID[teamsSubset$franchID == "STL"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "CHC"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "MIL"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "PIT"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "CIN"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "CLE"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "CHW"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "MIN"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "DET"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "KCR"] <- "Central"
teamsSubset$divID[teamsSubset$franchID == "ATL"] <- "East"
teamsSubset$divID[teamsSubset$franchID == "NYM"] <- "East"
teamsSubset$divID[teamsSubset$franchID == "PHI"] <- "East"
teamsSubset$divID[teamsSubset$franchID == "FLA"] <- "East"
teamsSubset$divID[teamsSubset$franchID == "WSN"] <- "East"
teamsSubset$divID[teamsSubset$franchID == "NYY"] <- "East"
teamsSubset$divID[teamsSubset$franchID == "TOR"] <- "East"
teamsSubset$divID[teamsSubset$franchID == "TBD"] <- "East"
teamsSubset$divID[teamsSubset$franchID == "BAL"] <- "East"
teamsSubset$divID[teamsSubset$franchID == "BOS"] <- "East"
teamsSubset$divID[teamsSubset$franchID == "LAD"] <- "West"
teamsSubset$divID[teamsSubset$franchID == "SDP"] <- "West"
teamsSubset$divID[teamsSubset$franchID == "SFG"] <- "West"
teamsSubset$divID[teamsSubset$franchID == "ARI"] <- "West"
teamsSubset$divID[teamsSubset$franchID == "COL"] <- "West"
teamsSubset$divID[teamsSubset$franchID == "HOU"] <- "West"
teamsSubset$divID[teamsSubset$franchID == "SEA"] <- "West"
teamsSubset$divID[teamsSubset$franchID == "ANA"] <- "West"
teamsSubset$divID[teamsSubset$franchID == "TEX"] <- "West"
teamsSubset$divID[teamsSubset$franchID == "OAK"] <- "West"

# rename lgID to currentLeague & name to team
teamsSubset <- rename(teamsSubset, currentLeague = lgID,
                      team = name)

#adding new columns
teamSubsetMutate <- teamsSubset %>%
  mutate(winPct = W/(W+L), 
         rpg = R/G, 
         hpg = H/G,
         tbpg = ((H + X2B + 2*X3B + 3*HR)/G), 
         hrpg = HR/G,
         bbpg = BB/G,
         avgAttendance = attendance/Ghome, 
         rapg = RA/G,
         hapg = HA/G,
         hrapg = HRA/G,
         bbapg = BBA/G,
         epg = E/G)

#removing columns that won't be used in final analysis
teamSubsetFinal <- teamSubsetMutate %>%
  select(-W, -L, -WCWin, -DivWin, -X2B, -X3B, 
         -AB, -SB, -CS, -HBP, -SF, -IPouts, -SO,
         -DP, -BPF, -PPF, -teamIDBR, -teamIDlahman45, 
         -teamIDretro, -Rank, -CG, -Ghome, -teamID, 
         -ER, -CG, -SHO, -SV, -SOA, -R, -H, -HR, -BB,
         -RA, -HA, -HRA, -BBA, -E, -park, -G, -attendance)

```


```{r EDA_Offensive}

o1 <- ggplot(teamSubsetFinal, aes(x = winPct, y = rpg))
o1 + geom_point(aes(color = WSWin))

o2 <- ggplot(teamSubsetFinal, aes(x = winPct, y = hpg))
o2 + geom_point(aes(color = WSWin))

o3 <- ggplot(teamSubsetFinal, aes(x = winPct, y = tbpg))
o3 + geom_point(aes(color = WSWin))

o4 <- ggplot(teamSubsetFinal, aes(x = winPct, y = hrpg))
o4 + geom_point(aes(color = WSWin))

o5 <- ggplot(teamSubsetFinal, aes(x = winPct, y = bbpg))
o5 + geom_point(aes(color = WSWin))

```

```{r EDA_Defensive}
d1 <- ggplot(teamSubsetFinal, aes(x = winPct, y = rapg))
d1 + geom_point(aes(color = WSWin))

d2 <- ggplot(teamSubsetFinal, aes(x=winPct, y = ERA))
d2 + geom_point(aes(color = WSWin))

d3 <- ggplot(teamSubsetFinal, aes(x=winPct, y = hapg))
d3 + geom_point(aes(color = WSWin))

d4 <- ggplot(teamSubsetFinal, aes(x=winPct, y = hrapg))
d4 + geom_point(aes(color = WSWin))

d5 <- ggplot(teamSubsetFinal, aes(x=winPct, y = bbapg))
d5 + geom_point(aes(color = WSWin))

d6 <- ggplot(teamSubsetFinal, aes(x=winPct, y = epg))
d6 + geom_point(aes(color = WSWin))

d7 <- ggplot(teamSubsetFinal, aes(x=winPct, y = FP))
d7 + geom_point(aes(color = WSWin))

```


```{r EDA_part3}

teamSubsetFinal2 <- teamSubsetFinal %>%
  filter(name == "Philadelphia Phillies")

n <- ggplot(teamSubsetFinal2, aes(x=yearID, y=winPct))
n + geom_line(color = "red") + 
  geom_point(size = 3, aes(shape = WSWin, color = LgWin)) + 
  labs(title = paste0("Percentage of Games Won by Year for ", teamSubsetFinal2$name),
       x = "Year", 
       y = "Percentage of Games Won")

```


```{r teamSummary}

teamWLSummary <- teamSubsetFinal %>%
  group_by(currentLeague, team) %>%
  mutate(winningSeason = ifelse(winPct > 0.5, 1, 0), 
         losingSeason = ifelse(winPct <= 0.5, 1, 0), 
         worldSeries = ifelse(WSWin == "Y", 1, 0), 
         leagueW = ifelse(LgWin == "Y", 1, 0)) %>%
  summarise(totalSeasons = sum(winningSeason, losingSeason),
            winningSeasons = sum(winningSeason), 
            losingSeasons = sum(losingSeason), 
            winningSeasonPct = winningSeasons/(losingSeasons+winningSeasons), 
            leagueWins = sum(leagueW), 
            worldSeriesWins = sum(worldSeries))

teamWSSummary <- teamSubsetFinal %>%
  group_by(team) %>%
  mutate(worldSeries = ifelse(WSWin == "Y", 1, 0), 
         leagueW = ifelse(LgWin == "Y", 1, 0)) %>%
  summarise(leagueWins = sum(leagueW), 
            worldSeriesWins = sum(worldSeries))



testing2 <- teamSubsetFinal %>%
  group_by(team) %>%
  filter(currentLeague == "NL" & divID == "Central") 


testgraph <- ggplot(data = testing2, aes(x = team, y = winPct)) 
testgraph + geom_boxplot()

testgraph2 <- ggplot(data = teamWSSummary, aes(team, ))


str(teamSubsetFinal)

```




